spring.application.name=API_GATEWAY
logging.level.root=INFO

# Port
server.port=${SERVER_PORT:8080}


# On coupe le bruit du serveur
logging.level.org.apache=warn
logging.level.org.springframework.web=info



# Écrire dans un fichier
logging.file.name=logs/app.log


