spring.application.name=ai-service
logging.level.root=INFO

# 2. Port 
server.port=${SERVER_PORT:}


# On met une fausse clé directement après les ":" pour que Spring Boot l'utilise par défaut
spring.ai.openai.api-key=${OPEN_AI_KEY:sk-fake-key-123456789}
spring.ai.openai.enabled=${OPENAI_ENABLED:false}

# Désactiver tous les modèles OpenAI au démarrage
spring.ai.model.chat=none
spring.ai.model.audio=none
spring.ai.model.image=none
spring.ai.model.embedding=none
spring.ai.model.moderation=none

# On coupe le bruit de Tomcat
logging.level.org.apache=warn
logging.level.org.springframework.web=info


# Écrire dans un fichier
logging.file.name=logs/app.log


