spring.application.name=s3-service
logging.level.root=INFO

# 2. Port 
server.port=${SERVER_PORT:8085}

# Configuration AWS
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY:}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY:}
cloud.aws.region.static=${AWS_REGION:}
aws.bucket.name=${AWS_BUCKET_NAME:}
cloud.aws.s3.enabled=${AWS_S3_ENABLED:false}

# On coupe le bruit de Tomcat
logging.level.org.apache=warn
logging.level.org.springframework.web=info

# Écrire dans un fichier
logging.file.name=logs/app.log