spring.application.name=${DATABASE_NAME:product-service}
logging.level.root=INFO

# 1. Base de données (L'URL contient déjà des variables, mais on s'assure que tout est propre)
spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
# Debogage ponctuel : lancer le service avec SPRING_JPA_SHOW_SQL=true
spring.jpa.show-sql=false
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect

# 2. Port 
server.port=${SERVER_PORT:8082}


# On coupe le bruit de Tomcat
logging.level.org.apache=warn
logging.level.org.springframework.web=info



# Écrire dans un fichier
logging.file.name=logs/app.log


