spring.application.name=${DATABASE_NAME:}
logging.level.root=INFO

# 1. Base de données (L'URL contient déjà des variables, mais on s'assure que tout est propre)
spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect

# 2. Port 
server.port=${SERVER_PORT:}

logging.level.org.springframework.web=trace
logging.level.org.apache=trace

# Configuration AWS
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY:}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY:}

# 3. Region AWS (Passage en variable)
cloud.aws.region.static=${AWS_REGION:}

# 4. Nom du Bucket S3 (Passage en variable)
aws.bucket.name=${AWS_BUCKET_NAME:}
cloud.aws.s3.enabled=${AWS_S3_ENABLED:false}

# Autres clés
spring.ai.openai.api-key=${OPEN_AI_KEY:}