spring.application.name=Ecommerce
logging.level.root=INFO
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
server.port=8080
logging.level.org.springframework.web=trace
logging.level.org.apache=trace


cloud.aws.credentials.access-key=${AWS_ACCESS_KEY:}


cloud.aws.credentials.secret-key=${AWS_SECRET_KEY:}


cloud.aws.region.static=eu-north-1

aws.bucket.name=buckets3tp2cloud
cloud.aws.s3.enabled=${AWS_S3_ENABLED:false}


spring.ai.openai.api-key=${OPEN_AI_KEY}
